---
applications:
- name: usda-fns-ingestor-temp
  stack: cflinuxfs4
  buildpack: python_buildpack
  memory: 512mb
  path: ../
  routes:
    - route: usda-dvs-dev-temp.app.cloud.gov
  instances: 1
  services:
   - usda-fns-ingestor-db
   - DJANGO
  env:
    DJANGO_SETTINGS_MODULE: usda_fns_ingestor.settings.cloud
