---
name: Deploy apps to cloud.gov
on:
  workflow_dispatch: null
  workflow_call:
    inputs:
      environment:
        required: true
        type: string

jobs:
  push-with-creds:
    name: Deploy to cloud.gov
    runs-on: ubuntu-latest
    # If you set up envirionments use this, I am hard coding for example
    # environment: ${{ inputs.environment }}
    environment: dev
    # env:
    #   space: ${{ inputs.environment }}
    env:
      space: dev
      CF_TRACE: true

    steps:
      - uses: actions/checkout@v2
      - name: Install pipdeptree
        run: pip install pipdeptree
      - name: Show dependency tree
        run: pipdeptree | grep -i statistics
      - name: Install dependencies (verbose)
        run: pip install -r usda_fns_ingestor/requirements.txt --verbose
      - name: Deploy to cloud.gov
        uses: 18f/cg-deploy-action@main
        with:
          cf_username: ${{ secrets.CF_USERNAME }}
          cf_password: ${{ secrets.CF_PASSWORD }}
          cf_org: usda-fns
          cf_space: ${{ env.space }}
          push_arguments: -f usda_fns_ingestor/manifests/manifest_${{ env.space }}.yml
