#---
#name: Deploy to cloud.gov
#on:
#  push:
#    branches:
#      - main
#    # tags:
#    #   - v1.*
#
#  pull_request:
#
#  workflow_dispatch: null
#
#jobs:
#  test-and-lint:
#    uses: ./.github/workflows/test.yml
#    secrets: inherit
#
#  # deploy to dev when there are updated to the main branch
#  deploy-dev:
#    name: Deploy dev app to cloud.gov
#    if: github.event.ref == 'refs/heads/main'
#    needs:
#      - test-and-lint
#    uses: ./.github/workflows/deploy-apps.yml
#    with:
#      environment: "dev"
#    secrets: inherit
#
#
#  # deploy to production
#  # deploy-production:
#  #   name: Deploy production to cloud.gov
#  #   if: startsWith(github.ref, 'refs/tags/v')
#  #   needs:
#  #     - test-and-lint
#  #   uses: ./.github/workflows/deploy-apps.yml
#  #   with:
#  #     environment: "production"
#  #   secrets: inherit